ESPN:
    SWID: '{483C569B-8A95-407D-A4E8-2E0F62824F16}'
    ESPN_S2: 'AEB0WyqD1HUQ0%2FBXr6q9zxQtIySN%2FJsISfcr6%2FjX4iNMGgBmzBtbMRjbfeTQb3xVf51vPEugSO3w8uh2TGva0eNuxqb%2F%2BsJTtUNyqrZscMuyerhRJxgmKfwOo8O5Kys56GUuuz%2BUjGgqPsnjq6xTvUcQXpJWpNBSH0pi9H3DIg8eDAk8RQTUwkywZtURXAkcFWTaUc2CUTUXI9CQZQQan9UMgPO0Uyk9z0tyX4taUV%2Fubz1a3mXR1UsfUDeI8RZrZZiJod83NAcxs84HFP9KsnQs'
    LEAGUEID: '1581399'